### PR TITLE
upgrade OTEL exporter to stable version

### PR DESCRIPTION
**Pull request by swaroopar**
fixes https://github.com/eclipse-xpanse/xpanse/issues/2036

### CODE REVIEW

**Comment by Alice1319** [comment]
LGTM

**Comment by baixinsui** [comment]
LGTM

**Comment by WangLiNaruto** [comment]
LGTM

**Comment by swaroopar** [comment]
@iskey Please review these user stories whenever possible.

**Review by iskey — APPROVED** [review]
LGTM

**Pull request merged**
