### PR TITLE
fix URI format

### LINKED ISSUE #307: update URI for serviceDetail method
Currently the URI for 

- listDeployedServices() -> is /services/deployed -> returns List<ServiceVo>
- serviceDetail() -> is /services/deployed/{id} -> returns ServiceDetailVo -> going by the URI format, I expected the method to return ServiceVo

To make it more clear, change the serviceDetail URI to -> /services/deployed/{id}/details

### PR DESCRIPTION
**Pull request by swaroopar**
fixes #307

### CODE REVIEW

**Review by iskey — CHANGES_REQUESTED** [review]
Looks good. But we should update the GUI at the same time.
I think @Alice1319 is working on this.

**Comment by swaroopar** [comment]
@iskey yes. GUI must be updated. Either someone else does it, or I can prepare the GUI also and we merge both PRs together.

**Comment by swaroopar** [comment]
@iskey i have opened a PR for UI with new generated client. We can merge both PRs together.

**Review by iskey — APPROVED** [review]
looks good.

**Pull request merged**
