### PR TITLE
Refine the resource Handler

### LINKED ISSUE #215: Refine the ResourceHandler for the deployment and Huawei plugin.

### PR DESCRIPTION
**Pull request by jinyangyang222**
fix #215 .

### CODE REVIEW

**Review by swaroopar — CHANGES_REQUESTED** [review]
sorry it is not clear to me which issue is this and what problem are we trying to solve.

**Review by swaroopar — APPROVED** [review]
looks good.

**Comment by iskey** [comment]
Please rebase your commits, and reset this branch.

**Comment by jinyangyang222** [comment]
@iskey Request review

**Review by iskey — APPROVED** [review]
looks good.

**Pull request merged**
