### PR TITLE
Add pbkdf2 encode/decode for deployment sensitive variables

### LINKED ISSUE #557: Add AES encode/decode for deployment sensitive variables

### PR DESCRIPTION
**Pull request by WangLiNaruto**
Fixed #557

### CODE REVIEW

**Review by swaroopar — CHANGES_REQUESTED** [review]
same question here as well. where and how is the decoding handled?

**Comment by iskey** [comment]
> same question here as well. where and how is the decoding handled?

My fault, I misremembered the pbkdf2 and AES, we should choose AES here.

**Comment by WangLiNaruto** [comment]
looks good

**Review by iskey — CHANGES_REQUESTED** [review]
Please turn to AES instead.

**Pull request closed without merging**
