### PR TITLE
Update the generation of openAPI document for adding credential

### PR DESCRIPTION
**Pull request by baixinsui**

### CODE REVIEW

**Review by swaroopar — CHANGES_REQUESTED** [review]
@baixinsui this PR has the changes from your other PR also. Is this  intentional or by mistake?

**Comment by baixinsui** [comment]
> this PR has the changes from your other PR also. Is this intentional or by mistake?

The commit [Update the generation of openAPI document for adding credential]  has a dependency on the other commit. I close this PR and reopen it after the another merged.

**Comment by baixinsui** [comment]
@iskey Please review this PR.

**Review by swaroopar — APPROVED** [review]
Looks good.

**Review by iskey — APPROVED** [review]
looks good.

**Pull request merged**
